[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
gitpython = "^3.1.44"
pandas = "^2.2.3"
matplotlib = "^3.9"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
